// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMOP___backend.Modelos;

public partial class cat_Categoria
{
    [Key]
    public int cat_codigo { get; set; }

    [Required]
    [StringLength(255)]
    public string cat_nombre { get; set; }

    [InverseProperty("pro_codCategoriaNavigation")]
    public virtual ICollection<pro_Proyecto> pro_Proyectos { get; set; } = new List<pro_Proyecto>();
}