// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMOP___backend.Modelos;

public partial class phi_proyectoHito
{
    [Key]
    public int phi_codigo { get; set; }

    public int phi_codproyecto { get; set; }

    [Required]
    [StringLength(200)]
    public string phi_nombre { get; set; }

    [Column(TypeName = "date")]
    public DateTime? phi_fechaInicio { get; set; }

    [Column(TypeName = "date")]
    public DateTime? phi_fechaFin { get; set; }

    [ForeignKey("phi_codproyecto")]
    [InverseProperty("phi_proyectoHitos")]
    public virtual pro_Proyecto phi_codproyectoNavigation { get; set; }

    [InverseProperty("pta_codHitoNavigation")]
    public virtual ICollection<pta_proyectoTarea> pta_proyectoTareas { get; set; } = new List<pta_proyectoTarea>();
}