// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMOP___backend.Modelos;

[Table("ppre_proyectoPresupuesto")]
public partial class ppre_proyectoPresupuesto
{
    [Key]
    public int ppre_codigo { get; set; }

    public int ppre_codproyecto { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ppre_monto { get; set; }

    [StringLength(300)]
    public string ppre_descripcion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ppre_fecha { get; set; }

    [ForeignKey("ppre_codproyecto")]
    [InverseProperty("ppre_proyectoPresupuestos")]
    public virtual pro_Proyecto ppre_codproyectoNavigation { get; set; }
}