// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMOP___backend.Modelos;

public partial class pro_Proyecto
{
    [Key]
    public int pro_codigo { get; set; }

    [Required]
    [StringLength(255)]
    public string pro_nombre { get; set; }

    [StringLength(1000)]
    public string pro_descripcion { get; set; }

    public int pro_codCategoria { get; set; }

    [StringLength(200)]
    public string pro_ubicacion { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal pro_presupuestoTotal { get; set; }

    [Column(TypeName = "date")]
    public DateTime? pro_fechaInicio { get; set; }

    [Column(TypeName = "date")]
    public DateTime? pro_fechaFinEstimada { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? pro_fechaCreacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? pro_fechaActualizacion { get; set; }

    [InverseProperty("phi_codproyectoNavigation")]
    public virtual ICollection<phi_proyectoHito> phi_proyectoHitos { get; set; } = new List<phi_proyectoHito>();

    [InverseProperty("ppre_codproyectoNavigation")]
    public virtual ICollection<ppre_proyectoPresupuesto> ppre_proyectoPresupuestos { get; set; } = new List<ppre_proyectoPresupuesto>();

    [ForeignKey("pro_codCategoria")]
    [InverseProperty("pro_Proyectos")]
    public virtual cat_Categoria pro_codCategoriaNavigation { get; set; }

    [InverseProperty("pta_codproyectoNavigation")]
    public virtual ICollection<pta_proyectoTarea> pta_proyectoTareas { get; set; } = new List<pta_proyectoTarea>();
}