// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SIMOP___backend.Modelos;

public partial class pta_proyectoTarea
{
    [Key]
    public int pta_codigo { get; set; }

    public int pta_codproyecto { get; set; }

    public int? pta_codHito { get; set; }

    [Required]
    [StringLength(300)]
    public string pta_Descripcion { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string pta_Estado { get; set; }

    [Column(TypeName = "date")]
    public DateTime? pta_FechaInicio { get; set; }

    [Column(TypeName = "date")]
    public DateTime? pta_FechaFin { get; set; }

    [ForeignKey("pta_codHito")]
    [InverseProperty("pta_proyectoTareas")]
    public virtual phi_proyectoHito pta_codHitoNavigation { get; set; }

    [ForeignKey("pta_codproyecto")]
    [InverseProperty("pta_proyectoTareas")]
    public virtual pro_Proyecto pta_codproyectoNavigation { get; set; }
}