// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SIMOP___backend.Modelos;

namespace SIMOP___backend.Context;

public partial class SIMOPContext : DbContext
{
    public SIMOPContext(DbContextOptions<SIMOPContext> options)
        : base(options)
    {
    }

    public virtual DbSet<cat_Categoria> cat_Categorias { get; set; }

    public virtual DbSet<phi_proyectoHito> phi_proyectoHitos { get; set; }

    public virtual DbSet<ppre_proyectoPresupuesto> ppre_proyectoPresupuestos { get; set; }

    public virtual DbSet<pro_Proyecto> pro_Proyectos { get; set; }

    public virtual DbSet<pta_proyectoTarea> pta_proyectoTareas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<cat_Categoria>(entity =>
        {
            entity.HasKey(e => e.cat_codigo).HasName("PK__cat_Cate__38ABB93F9308C767");
        });

        modelBuilder.Entity<phi_proyectoHito>(entity =>
        {
            entity.HasKey(e => e.phi_codigo).HasName("PK__phi_proy__8953785AEE6E327B");

            entity.HasOne(d => d.phi_codproyectoNavigation).WithMany(p => p.phi_proyectoHitos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__phi_proye__phi_c__76969D2E");
        });

        modelBuilder.Entity<ppre_proyectoPresupuesto>(entity =>
        {
            entity.HasKey(e => e.ppre_codigo).HasName("PK__ppre_pro__511495E79F77F4B7");

            entity.Property(e => e.ppre_fecha).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.ppre_codproyectoNavigation).WithMany(p => p.ppre_proyectoPresupuestos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ppre_proy__ppre___7E37BEF6");
        });

        modelBuilder.Entity<pro_Proyecto>(entity =>
        {
            entity.HasKey(e => e.pro_codigo).HasName("PK__pro_Proy__25CC172E32C920D7");

            entity.Property(e => e.pro_fechaActualizacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.pro_fechaCreacion).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.pro_codCategoriaNavigation).WithMany(p => p.pro_Proyectos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__pro_Proye__pro_f__73BA3083");
        });

        modelBuilder.Entity<pta_proyectoTarea>(entity =>
        {
            entity.HasKey(e => e.pta_codigo).HasName("PK__pta_proy__16BD481A1EE19D4D");

            entity.HasOne(d => d.pta_codHitoNavigation).WithMany(p => p.pta_proyectoTareas).HasConstraintName("FK__pta_proye__pta_c__7A672E12");

            entity.HasOne(d => d.pta_codproyectoNavigation).WithMany(p => p.pta_proyectoTareas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__pta_proye__pta_c__797309D9");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}